### ISSUE TITLE
Empty version range for statistics dependency on Hackage

### ISSUE THREAD

**Issue by k0ral** [alpmestan/probable#7]
On Hackage, the [current revision](http://hackage.haskell.org/package/probable-0.1.3/revision/2.cabal) of `probable` specifies the following dependency:
```
statistics >= 0.14 && <0.14
```

The constraint is obviously impossible to fulfill. I guess this is a mistake, considering that in this repository, the dependency is specified like this:
```
statistics >= 0.14,
```

Could you please fix it on Hackage ?

**Comment by alpmestan** [comment]
Oops, sorry about that @k0ral :)

I made it `>= 0.14 && <0.15`, since IIRC someone reported it wouldn't build with statistics 0.15. I should look into that and publish a new version that works with `statistics-0.15`, one of these days.

**Comment by k0ral** [comment]
Thank you. Closing this issue.
